//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_default_grab;
        
        private static SteamVR_Action_Boolean p_default_togglePlayback;
        
        private static SteamVR_Action_Vector2 p_default_joystick;
        
        private static SteamVR_Action_Single p_default_interactUI;
        
        private static SteamVR_Action_Pose p_default_Pose;
        
        public static SteamVR_Action_Boolean default_grab
        {
            get
            {
                return SteamVR_Actions.p_default_grab.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_togglePlayback
        {
            get
            {
                return SteamVR_Actions.p_default_togglePlayback.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 default_joystick
        {
            get
            {
                return SteamVR_Actions.p_default_joystick.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Single default_interactUI
        {
            get
            {
                return SteamVR_Actions.p_default_interactUI.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Pose default_Pose
        {
            get
            {
                return SteamVR_Actions.p_default_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.default_grab,
                    SteamVR_Actions.default_togglePlayback,
                    SteamVR_Actions.default_joystick,
                    SteamVR_Actions.default_interactUI,
                    SteamVR_Actions.default_Pose};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_grab,
                    SteamVR_Actions.default_togglePlayback,
                    SteamVR_Actions.default_joystick,
                    SteamVR_Actions.default_interactUI,
                    SteamVR_Actions.default_Pose};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[0];
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[0];
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.default_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.default_grab,
                    SteamVR_Actions.default_togglePlayback};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.default_interactUI};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.default_joystick};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_grab,
                    SteamVR_Actions.default_togglePlayback,
                    SteamVR_Actions.default_joystick,
                    SteamVR_Actions.default_interactUI};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_grab = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/grab")));
            SteamVR_Actions.p_default_togglePlayback = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/togglePlayback")));
            SteamVR_Actions.p_default_joystick = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/default/in/joystick")));
            SteamVR_Actions.p_default_interactUI = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/default/in/interactUI")));
            SteamVR_Actions.p_default_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default/in/Pose")));
        }
    }
}
