//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean grab
        {
            get
            {
                return SteamVR_Actions.default_grab;
            }
        }
        
        public virtual SteamVR_Action_Boolean togglePlayback
        {
            get
            {
                return SteamVR_Actions.default_togglePlayback;
            }
        }
        
        public virtual SteamVR_Action_Vector2 joystick
        {
            get
            {
                return SteamVR_Actions.default_joystick;
            }
        }
        
        public virtual SteamVR_Action_Single interactUI
        {
            get
            {
                return SteamVR_Actions.default_interactUI;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
    }
}
